-- Ritmo Brasil (RB) - Database Schema
-- Optimized for PostgreSQL with PostGIS extension for Geospatial data

-- 1. Profiles & Users
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    subscription_status TEXT DEFAULT 'free', -- 'free', 'premium'
    profile_data JSONB -- {age, weight, height, gender, injuries, objective}
);

-- 2. Workout Plans (Generated by AI)
CREATE TABLE IF NOT EXISTS workout_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    ai_logic_version TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- 3. Workout Sessions (The actual runs)
CREATE TABLE IF NOT EXISTS workout_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES workout_plans(id) ON DELETE SET NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Metrics
    total_distance_km NUMERIC(10,2) NOT NULL,
    total_time_seconds INTEGER NOT NULL,
    average_pace_per_km TEXT, -- e.g. "5:24"
    calories_burned INTEGER,
    average_heart_rate INTEGER,

    -- Spatial data (requires PostGIS)
    -- route_path GEOMETRY(LineString, 4326),

    -- AI Analysis
    ai_feedback_text TEXT,
    performance_seal TEXT, -- 'EXCELLENT', 'CONSISTENT', etc.
    needs_adjustment BOOLEAN DEFAULT FALSE
);

-- 4. Achievement Badges
CREATE TABLE IF NOT EXISTS achievements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    badge_name TEXT NOT NULL,
    earned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Intelligent Training Calendar
CREATE TABLE IF NOT EXISTS training_schedule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    scheduled_date DATE NOT NULL,
    workout_type TEXT NOT NULL, -- 'Intervalado', 'Rodagem', 'Tempo Run', 'Descanso'
    target_distance_km NUMERIC(10,2),
    target_pace TEXT,
    status TEXT DEFAULT 'PENDING', -- 'PENDING', 'COMPLETED', 'MISSED', 'RESCHEDULED'
    actual_session_id UUID REFERENCES workout_sessions(id) ON DELETE SET NULL,
    is_regenerative_week BOOLEAN DEFAULT FALSE
);

-- 6. Recovery & Fatigue Management
CREATE TABLE IF NOT EXISTS user_recovery_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fatigue_score NUMERIC(5,2), -- 0.00 to 1.00
    resting_heart_rate INTEGER,
    sleep_quality_score INTEGER,
    readiness_status TEXT -- 'READY', 'CAUTION', 'RECOVERY_MODE'
);

-- 8. Live GPS Sync (Real-time points)
CREATE TABLE IF NOT EXISTS live_session_coords (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    workout_id UUID NOT NULL,
    lat NUMERIC(10,7) NOT NULL,
    lng NUMERIC(10,7) NOT NULL,
    speed NUMERIC(5,2),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Habilitar o Realtime para esta tabela no Supabase
-- ALTER PUBLICATION supabase_realtime ADD TABLE live_session_coords;
